AWSTemplateFormatVersion: 2010-09-09
Description:  >-
  Create an admin user with all rights access as long as they used MFA.
  Is it still necessary to go to IAM console and define a password and MFA device
Parameters:
  Username:
    Type: String
    Description: Enter the username that will be admin with MFA enforced
Resources:
  CFNAdminsGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
      - 'arn:aws:iam::aws:policy/job-function/Billing'
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref 'Username'
  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref CFNUser
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref CFNAdminsGroup
      Users:
      - !Ref CFNUser
  CFNforceMFA:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: forceMFA
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action: '*'
            Resource: '*'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: 'false'
      Groups:
        - !Ref CFNAdminsGroup

Outputs:
  UserName:
    Value: !Ref 'Username'
    Description: Username
  AccessKey:
    Value: !Ref CFNKeys
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt 
      - CFNKeys
      - SecretAccessKey
    Description: AWSSecretKey of new user
  MFA:
    Value: 'You must enable MFA yourself for this user'
    Description: Information
