version: '3'

services:
  vpn:
    image: ipsec-vpn-server-private
    network_mode: bridge
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    restart: always
    # env_file:
    #   - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_USER=vpnuser
